apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: autoops
  template:
    metadata:
      labels:
        app: autoops
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: autoops
        image: autoops:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5